Feature/5972 index algorithm optimization
aodn/es-indexer pull request #165
Opened 2024-11-06 03:09 UTC by HavierD

Features are not perfect yet. It will possibly be optimized in the future according to the frontend performance tests.

2024-11-07 05:19 UTC, utas-raymondng requested changes

2024-11-07 05:19 UTC, utas-raymondng commented on indexer/src/main/java/au/org/aodn/esindexer/service/IndexerServiceImpl.java
> +    public List<BulkResponse> indexDataset(String uuid, LocalDate startDate, LocalDate endDate) {
Without using ComplableFuture, you may get timeout for long running operation, you think it is ok?

2024-11-12 23:53 UTC, HavierD commented
https://github.com/aodn/backlog/issues/6081      new ticket to do the refactoring

2024-11-13 00:55 UTC, utas-raymondng requested changes
one more minor change

2024-11-13 00:55 UTC, utas-raymondng commented on indexer/src/main/java/au/org/aodn/esindexer/service/DataAccessServiceImpl.java
>      private final RestTemplate restTemplate = new RestTemplate();
Please user @Autowired for restTemplate

2024-11-13 00:58 UTC, utas-raymondng approved these changes
LGTM

2024-11-13 01:10 UTC, merged

2024-11-13 01:10 UTC, utas-raymondng commented
> [aodn/backlog#6081](https://github.com/aodn/backlog/issues/6081) new ticket to do the refactoring

I guess you will add test case to cover your change right?

2024-11-13 22:37 UTC, HavierD commented
> > [aodn/backlog#6081](https://github.com/aodn/backlog/issues/6081) new ticket to do the refactoring
> 
> I guess you will add test case to cover your change right?

Yes all the new features about real dataset in es-indexer, ogc-api, and frontend will be added test cases when the features are all stable. Currently i am still changing them.