CICD pipeline github actions
aodn/es-indexer pull request #40
Opened 2023-12-05 03:33 UTC by priyaranjanpatil

-Currently CI/CD pipeline built for only DEV env
-Latest version will be auto deployed and also can rollback to previous versions
-We are using Dockerfile to build and push images to ECR & ECS also Env vars will be part of ECS task defnition
-Docker image scan is added in the pipeline which is using Trivy vulnerability scanner
-Environment variables
Platform specific: are stored in AWS SSM paramater store and pulled in Github actions while running pipeline
App specific: are stored in Github actions Env variables

2023-12-05 04:30 UTC, nandeeshsb9 approved these changes

2023-12-05 05:09 UTC, vietnguyengit requested changes
Please clean up the commit history

2023-12-05 05:14 UTC, vietnguyengit requested changes

2023-12-05 05:14 UTC, vietnguyengit commented on .dockerignore
> +.env
missing ending line

2023-12-05 05:14 UTC, vietnguyengit commented on Dockerfile
> +CMD ["java", "-jar", "app.jar"]
missing ending line

2023-12-05 05:15 UTC, vietnguyengit commented on .github/workflows/github-actions.yml
> +          wait-for-service-stability: true
missing ending line

2023-12-05 05:18 UTC, vietnguyengit requested changes
also please put back the `ecr-build,yml` if this PR won't immediately have the ECS instance available @priyaranjanpatil

 removing `ecs-build.yml` will disrupt current process for refreshing the indexer instance we need.

2023-12-05 05:35 UTC, vietnguyengit commented on aodn-es-indexer-td.json
> +}
missing ending line

2023-12-06 00:06 UTC, priyaranjanpatil commented
closing this PR and will open another one after resolving merge and rebase to main

2023-12-06 00:06 UTC, closed without merging

2023-12-06 00:40 UTC, vietnguyengit commented
thanks @priyaranjanpatil that's good, rebasing should be with `git rebase` command always, please also organise the commits history when you work on new branch and create new PR, you don't need to push every new commits you have locally, which will create a mess in git log unnecessarily, but if they are for github action, which you have to push to remote branch to see actual affects, when you are happy with changes you've made:

your can run commands like these to rewrite the commits history with `git reset --soft HEAD~<number of commits>`:

or you can do git squash with iterative mode to pick and squash whatever commits in the log